In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [17]:
df=pd.read_csv(r"d:/Downloads_ML_aaa/train.csv",usecols=["Age","Parch","SibSp",
                                                         "Survived","Pclass"])

In [18]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [19]:
df.dropna(inplace=True)

In [20]:
X=df.iloc[:,1:]
y=df["Survived"]
np.mean(cross_val_score(LogisticRegression(),X,y,scoring="accuracy",cv=20))

np.float64(0.6933333333333332)

## Applying feature Construction

In [21]:
X["Family_size"]=X["SibSp"]+X["Parch"]+1

In [22]:
# making the function
def family_size(num):
    if num==1:
        # alone
        return 0
    elif num<=4:
        return 1
    else:
        return 2

In [23]:
X["Family_type"]=X["Family_size"].apply(family_size)

In [25]:
X.head()

   Pclass   Age  SibSp  Parch  Family_size  Family_type
0       3  22.0      1      0            2            1
1       1  38.0      1      0            2            1
2       3  26.0      0      0            1            0
3       1  35.0      1      0            2            1
4       3  35.0      0      0            1            0

In [27]:
X.drop(columns=["SibSp","Parch","Family_size"])

     Pclass   Age  Family_type
0         3  22.0            1
1         1  38.0            1
2         3  26.0            0
3         1  35.0            1
4         3  35.0            0
..      ...   ...          ...
885       3  39.0            2
886       2  27.0            0
887       1  19.0            0
889       1  26.0            0
890       3  32.0            0

[714 rows x 3 columns]

In [28]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring="accuracy",cv=20))

np.float64(0.7031746031746031)

## Feature splitting example

In [29]:
df2=pd.read_csv(r"d:/Downloads_ML_aaa/train.csv")

In [33]:
df2["Title"]=df2["Name"].str.split(",",expand=True)[1].str.split(".",expand=True)[0]
df2["Title"]

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: Title, Length: 891, dtype: object

In [35]:
salutation=df2.groupby("Title")
salutation["Survived"].mean()*100

Title
Capt              0.000000
Col              50.000000
Don               0.000000
Dr               42.857143
Jonkheer          0.000000
Lady            100.000000
Major            50.000000
Master           57.500000
Miss             69.780220
Mlle            100.000000
Mme             100.000000
Mr               15.667311
Mrs              79.200000
Ms              100.000000
Rev               0.000000
Sir             100.000000
the Countess    100.000000
Name: Survived, dtype: float64